(ns zil.bridge.formal-feedback
  "Emit BackendCapabilities/FormalFeedbackSchema-compatible sidecar facts
   from proof-obligation execution reports."
  (:require [clojure.java.io :as io]
            [clojure.string :as str]))

(defn- token->name
  [v]
  (cond
    (string? v) v
    (keyword? v) (name v)
    (symbol? v) (name v)
    :else (str v)))

(defn- sanitize-id
  [v]
  (let [txt (-> (token->name v)
                str/lower-case
                (str/replace #"[^a-z0-9]+" "_")
                (str/replace #"^_+" "")
                (str/replace #"_+$" ""))]
    (if (str/blank? txt) "x" txt)))

(defn- quoted
  [s]
  (pr-str (str (or s ""))))

(defn- fact-line
  [object relation subject]
  (str object "#" relation "@" subject "."))

(defn- bfc-tool
  [tool]
  (case tool
    :z3 "tool:z3"
    :lean4 "tool:lean4"
    :tlaps "tool:tla"
    :acl2 "tool:acl2"
    "tool:z3"))

(defn- required-capability
  [tool-subject]
  (case tool-subject
    "tool:z3" "capability:check_z3"
    "tool:lean4" "capability:emit_lean4"
    "tool:tla" "capability:emit_tla"
    "tool:acl2" "capability:check_acl2"
    nil))

(defn- feedback-verdict
  [status]
  (case status
    :satisfied "value:satisfied"
    :violated "value:violated"
    :unknown "value:unknown"
    :error "value:error"
    nil))

(defn- obligation-criticality
  [{:keys [criticality]}]
  (let [v (some-> criticality token->name str/lower-case)]
    (case v
      "low" "value:low"
      "high" "value:high"
      "value:low" "value:low"
      "value:high" "value:high"
      "value:medium" "value:medium"
      "value:medium")))

(defn- file-stem
  [path]
  (let [name (.getName (io/file path))
        idx (.lastIndexOf name ".")]
    (if (pos? idx)
      (subs name 0 idx)
      name)))

(defn- ensure-parent!
  [path]
  (let [f (io/file path)
        p (.getParentFile f)]
    (when p
      (.mkdirs p))
    (.getAbsolutePath f)))

(defn- obligation-records
  [obligations]
  (->> obligations
       (map-indexed
        (fn [idx ob]
          (let [base (sanitize-id (or (:name ob) (:id ob)))
                n (inc idx)
                oid (format "o_%03d_%s" n base)
                fid (format "f_%03d_%s" n base)
                tool-subject (bfc-tool (:tool ob))]
            {:idx n
             :id oid
             :feedback-id fid
             :tool tool-subject
             :capability (required-capability tool-subject)
             :criticality (obligation-criticality ob)
             :verdict (feedback-verdict (:status ob))
             :evidence (str "evidence:" (format "proof_obligation_%03d" n))})))
       vec))

(defn- render-feedback-module
  [{:keys [module-name source-path summary-json-path run-id backend-id artifact-id revision obligations]}]
  (let [rows (obligation-records obligations)
        lines (transient [])]
    (doseq [line [(str "MODULE " module-name ".")
                  ""
                  "// Generated by vstack-ci formal feedback bridge."
                  "// Sidecar facts follow BackendCapabilities/FormalFeedbackSchema vocabulary."
                  ""]]
      (conj! lines line))

    (doseq [line [(fact-line (str "backend:" backend-id) "kind" "entity:backend_engine")
                  (fact-line (str "backend:" backend-id) "engine" "value:clj")
                  (fact-line (str "backend:" backend-id) "profile" "value:vstack_ci")
                  (fact-line (str "backend:" backend-id) "enabled" "value:true")
                  (fact-line (str "backend:" backend-id) "capability" "capability:check_z3")
                  (fact-line (str "backend:" backend-id) "capability" "capability:check_acl2")
                  (fact-line (str "backend:" backend-id) "capability" "capability:emit_tla")
                  (fact-line (str "backend:" backend-id) "capability" "capability:emit_lean4")
                  (fact-line (str "backend:" backend-id) "capability" "capability:emit_acl2")
                  (fact-line (str "backend:" backend-id) "capability" "capability:ingest_feedback")
                  (fact-line (str "backend:" backend-id) "capability" "capability:artifact_json")
                  (fact-line (str "backend:" backend-id) "bridge_tool" "tool:z3")
                  (fact-line (str "backend:" backend-id) "bridge_tool" "tool:tla")
                  (fact-line (str "backend:" backend-id) "bridge_tool" "tool:lean4")
                  (fact-line (str "backend:" backend-id) "bridge_tool" "tool:acl2")
                  (fact-line (str "backend:" backend-id) "bridge_mode" "value:direct")
                  (fact-line (str "backend:" backend-id) "version" "value:vstack_ci_0_1")
                  ""]]
      (conj! lines line))

    (doseq [line [(fact-line (str "run:" run-id) "kind" "entity:backend_run")
                  (fact-line (str "run:" run-id) "module" (str "value:" module-name))
                  (fact-line (str "run:" run-id) "revision" (str "revision:" revision))
                  (fact-line (str "run:" run-id) "backend" (str "backend:" backend-id))
                  (fact-line (str "run:" run-id) "source" (quoted source-path))
                  ""]]
      (conj! lines line))

    (doseq [line [(fact-line (str "artifact:" artifact-id) "kind" "entity:interop_artifact")
                  (fact-line (str "artifact:" artifact-id) "format" "value:json")
                  (fact-line (str "artifact:" artifact-id) "uri" "uri:vstack_summary_json")
                  (fact-line (str "artifact:" artifact-id) "schema_id" "value:schema_formal_feedback_v1")
                  (fact-line (str "artifact:" artifact-id) "local_path" (quoted summary-json-path))
                  (fact-line (str "artifact:" artifact-id) "producer" "tool:z3")
                  (fact-line (str "artifact:" artifact-id) "consumer" (str "backend:" backend-id))
                  (fact-line (str "run:" run-id) "output_artifact" (str "artifact:" artifact-id))
                  ""]]
      (conj! lines line))

    (doseq [{:keys [id tool capability criticality]} rows]
      (doseq [line [(fact-line (str "obligation:" id) "kind" "entity:formal_obligation")
                    (fact-line (str "obligation:" id) "class" "value:consistency")
                    (fact-line (str "obligation:" id) "criticality" criticality)
                    (fact-line (str "obligation:" id) "run" (str "run:" run-id))
                    (fact-line (str "obligation:" id) "artifact" (str "artifact:" artifact-id))
                    (fact-line (str "obligation:" id) "target_tool" tool)]]
        (conj! lines line))
      (when capability
        (conj! lines (fact-line (str "obligation:" id) "requires_capability" capability)))
      (conj! lines ""))

    (doseq [{:keys [id feedback-id tool verdict evidence]} rows
            :when verdict]
      (doseq [line [(fact-line (str "feedback:" feedback-id) "kind" "entity:formal_feedback")
                    (fact-line (str "feedback:" feedback-id) "run" (str "run:" run-id))
                    (fact-line (str "feedback:" feedback-id) "obligation" (str "obligation:" id))
                    (fact-line (str "feedback:" feedback-id) "tool" tool)
                    (fact-line (str "feedback:" feedback-id) "verdict" verdict)
                    (fact-line (str "feedback:" feedback-id) "artifact" (str "artifact:" artifact-id))
                    (fact-line (str "feedback:" feedback-id) "evidence" evidence)
                    ""]]
        (conj! lines line)))

    (doseq [line ["QUERY vstack_feedback_obligation_status:"
                  "FIND ?obligation ?status WHERE ?obligation#kind@entity:formal_obligation AND ?obligation#status@?status."
                  ""
                  "QUERY vstack_feedback_run_status:"
                  "FIND ?run ?status WHERE ?run#kind@entity:backend_run AND ?run#status@?status."
                  ""
                  "QUERY vstack_feedback_matrix:"
                  "FIND ?run ?obligation ?tool ?verdict WHERE ?run#kind@entity:backend_run AND ?obligation#kind@entity:formal_obligation AND ?feedback#run@?run AND ?feedback#obligation@?obligation AND ?feedback#tool@?tool AND ?feedback#verdict@?verdict."
                  ""]]
      (conj! lines line))

    (str/join "\n" (persistent! lines))))

(defn export-proof-obligations->formal-feedback
  "Write a formal-feedback sidecar module from `proof-obligation-check` report."
  [{:keys [path obligations]} {:keys [output-path module-name summary-json-path revision]}]
  (when-not output-path
    (throw (ex-info "Missing :output-path for formal feedback export." {})))
  (let [stem (file-stem path)
        output* (ensure-parent! output-path)
        module* (or module-name (str stem ".vstack.feedback"))
        run-id (str "run_" (sanitize-id stem))
        backend-id "b_vstack_ci_main"
        artifact-id "a_vstack_summary"
        revision* (or revision
                      (let [d (java.time.LocalDate/now)]
                        (str "rev_" (.getYear d)
                             (format "%02d" (.getMonthValue d))
                             (format "%02d" (.getDayOfMonth d)))))
        text (render-feedback-module {:module-name module*
                                      :source-path path
                                      :summary-json-path summary-json-path
                                      :run-id run-id
                                      :backend-id backend-id
                                      :artifact-id artifact-id
                                      :revision revision*
                                      :obligations obligations})]
    (spit output* text)
    {:ok true
     :path path
     :module module*
     :output_path output*
     :run_id run-id
     :backend_id backend-id
     :obligation_count (count obligations)
     :feedback_count (count (remove nil? (map feedback-verdict (map :status obligations))))}))
