#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(CDPATH= cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=scripts/lib/common.sh
source "$SCRIPT_DIR/lib/common.sh"

profile="full"
prefix="${ZIL_SETUP_PREFIX:-$HOME/.local}"
install_tools=false
build=true
run_tests=false
test_profile=""
offline=false
report="$ZIL_ROOT/.zil/setup-report.tsv"

usage() {
  cat <<'EOF'
Usage: bash scripts/setup.sh [options]

Options:
  --profile lean|full|extensions|legacy
  --install-tools       Install missing Elan and/or official Clojure CLI
  --prefix DIR          User installation prefix for Clojure CLI (default: ~/.local)
  --no-build            Diagnose and prepare dependencies without building
  --test                Run the profile's default tests after setup
  --test-profile NAME   Run a specific scripts/test.sh profile
  --offline             Do not download or install missing tools
  --report FILE         Setup report path (default: .zil/setup-report.tsv)

The script never installs Java, Git, Docker, Make, or OS packages and never uses
sudo. Install those prerequisites explicitly when the doctor reports them missing.
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --profile)
      [[ $# -ge 2 ]] || zil_die '--profile requires a value'
      profile="$2"
      shift 2
      ;;
    --install-tools)
      install_tools=true
      shift
      ;;
    --prefix)
      [[ $# -ge 2 ]] || zil_die '--prefix requires a value'
      prefix="$2"
      shift 2
      ;;
    --no-build)
      build=false
      shift
      ;;
    --test)
      run_tests=true
      shift
      ;;
    --test-profile)
      [[ $# -ge 2 ]] || zil_die '--test-profile requires a value'
      run_tests=true
      test_profile="$2"
      shift 2
      ;;
    --offline)
      offline=true
      shift
      ;;
    --report)
      [[ $# -ge 2 ]] || zil_die '--report requires a value'
      report="$2"
      shift 2
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    *)
      zil_die "unknown setup option: $1"
      ;;
  esac
done

case "$profile" in
  lean|full|extensions|legacy) ;;
  *) zil_die "unknown setup profile: $profile" ;;
esac

prefix="$(zil_abs_path "$prefix")"
report="$(zil_abs_path "$report")"
mkdir -p "$prefix/bin" "$ZIL_ROOT/.zil"
export PATH="$HOME/.elan/bin:$prefix/bin:$PATH"

require_installer_command() {
  local name="$1"
  zil_command_exists "$name" || zil_die "$name is required to install missing tools"
}

install_elan() {
  if zil_command_exists elan; then
    return
  fi
  [[ "$install_tools" == true ]] || return
  [[ "$offline" != true ]] || zil_die 'Elan is missing and --offline forbids installation'
  require_installer_command curl
  zil_log 'installing Elan without a default global toolchain'
  curl --fail --location --silent --show-error \
    https://elan.lean-lang.org/elan-init.sh | \
    sh -s -- -y --default-toolchain none
  export PATH="$HOME/.elan/bin:$PATH"
}

install_clojure_cli() {
  if zil_command_exists clojure && clojure -Sdescribe >/dev/null 2>&1; then
    return
  fi
  [[ "$install_tools" == true ]] || return
  [[ "$offline" != true ]] || zil_die 'Clojure CLI is missing and --offline forbids installation'
  zil_command_exists java || zil_die 'Java is required before installing the Clojure CLI'
  require_installer_command curl
  require_installer_command tar
  require_installer_command gzip
  local installer temp_dir install_url
  temp_dir="$(zil_temp_dir)"
  installer="$temp_dir/posix-install.sh"
  install_url="${CLOJURE_INSTALL_URL:-https://github.com/clojure/brew-install/releases/latest/download/posix-install.sh}"
  zil_log "installing the official Clojure CLI under $prefix"
  curl --fail --location --retry 3 --silent --show-error \
    "$install_url" --output "$installer"
  chmod +x "$installer"
  bash "$installer" --prefix "$prefix"
  rm -rf "$temp_dir"
  export PATH="$prefix/bin:$PATH"
}

install_elan
case "$profile" in
  full|extensions|legacy) install_clojure_cli ;;
esac

bash "$SCRIPT_DIR/doctor.sh" --profile "$profile" \
  --report "$ZIL_ROOT/.zil/doctor-$profile.tsv"

cd "$ZIL_ROOT"

if [[ "$build" == true ]]; then
  case "$profile" in
    lean)
      zil_log 'building the Lean SDK'
      lake build
      ;;
    full)
      zil_log 'resolving Clojure dependencies'
      clojure -Spath >/dev/null
      zil_log 'building the Lean package'
      lake build
      ;;
    extensions)
      zil_log 'resolving Clojure dependencies'
      clojure -Spath >/dev/null
      ;;
    legacy)
      zil_log 'resolving Clojure dependencies and building the standalone JAR'
      clojure -Spath >/dev/null
      bash bin/build-jar
      ;;
  esac
fi

cat > "$ZIL_ROOT/.zil/setup.env" <<EOF
# Generated by scripts/setup.sh. Source this file in a compatible shell.
export ZIL_HOME="$ZIL_ROOT"
export PATH="$HOME/.elan/bin:$prefix/bin:\$PATH"
EOF

zil_mkdir_parent "$report"
{
  printf 'ZIL-SETUP-REPORT/1\n'
  printf 'profile\t%s\n' "$profile"
  printf 'root\t%s\n' "$(zil_tsv_escape "$ZIL_ROOT")"
  printf 'prefix\t%s\n' "$(zil_tsv_escape "$prefix")"
  printf 'os\t%s\n' "$(zil_os)"
  printf 'arch\t%s\n' "$(zil_arch)"
  printf 'build\t%s\n' "$build"
  printf 'offline\t%s\n' "$offline"
  if zil_command_exists elan; then printf 'elan\t%s\n' "$(zil_tsv_escape "$(zil_first_line elan --version)")"; fi
  if zil_command_exists lean; then printf 'lean\t%s\n' "$(zil_tsv_escape "$(zil_first_line lean --version)")"; fi
  if zil_command_exists lake; then printf 'lake\t%s\n' "$(zil_tsv_escape "$(zil_first_line lake --version)")"; fi
  if zil_command_exists java; then printf 'java\t%s\n' "$(zil_tsv_escape "$(zil_first_line java --version)")"; fi
  if zil_command_exists clojure; then printf 'clojure-cli\tavailable\n'; fi
  printf 'result\tpass\n'
} > "$report"

zil_log "setup report: $report"
zil_log "environment file: $ZIL_ROOT/.zil/setup.env"

if [[ "$run_tests" == true ]]; then
  if [[ -z "$test_profile" ]]; then
    case "$profile" in
      lean) test_profile=lean ;;
      extensions) test_profile=clojure ;;
      full) test_profile=smoke ;;
      legacy) test_profile=clojure ;;
    esac
  fi
  zil_log "running test profile: $test_profile"
  bash "$SCRIPT_DIR/test.sh" --profile "$test_profile"
fi

zil_log "setup complete for profile '$profile'"
