#!/usr/bin/env python3
"""
splunk-activity-to-zil.py — Convert a Splunk SFTP activity CSV export into ZIL facts.

Usage:
    python3 splunk-activity-to-zil.py <input.csv> <output.zc> [--server-id SERVER_ID]
                                       [--window-start YYYY-MM-DD] [--window-end YYYY-MM-DD]
                                       [--window-days N] [--module MODULE_NAME]

Splunk query to export (save as CSV via "Export > CSV"):

    index=<idx> sourcetype=<st> source="*transfer*" type=CLOSE earliest=-365d
    | eval server_id='server-id'
    | stats
        last(_time) as last_activity_epoch
        count as transfer_count
        sum(bytes-out) as total_bytes
        dc(session-id) as session_count
        dc(source-ip) as ip_count
        values(source-ip) as source_ips
        values(path) as paths
      BY username, server_id
    | eval last_activity=strftime(last_activity_epoch, "%Y-%m-%d")
    | fields username, server_id, last_activity, transfer_count, total_bytes, session_count, source_ips, paths
    | sort server_id, username

Expected CSV columns (flexible — extras are ignored):
    username, server_id, last_activity, transfer_count, total_bytes, session_count
    source_ips      (optional, space/comma/pipe-separated)
    paths           (optional, space/comma/pipe-separated; script extracts prefixes)

The server_id in the CSV must match the ZIL token used in the model
(e.g. "s_1234567890abcdef0" with underscores, or "s-1234567890abcdef0" with hyphens —
the script normalizes hyphens to underscores).

If --server-id is supplied it overrides the server_id column for all rows (useful
when exporting a single-server search that doesn't include server_id).
"""

import argparse
import csv
import os
import re
import sys
from datetime import date, datetime


# ---------------------------------------------------------------------------
# Token normalization
# ---------------------------------------------------------------------------

def _token(raw: str) -> str:
    """Normalize a string to a valid ZIL identifier token."""
    t = raw.strip().lower()
    t = re.sub(r"[^a-z0-9_]", "_", t)
    t = re.sub(r"_+", "_", t)
    t = t.strip("_")
    return t or "unknown"


def _prefix_from_path(path: str) -> str:
    """Extract the directory prefix from a file path."""
    parts = path.rstrip("/").rsplit("/", 1)
    return parts[0] if len(parts) > 1 else "/"


def _split_multival(raw: str) -> list[str]:
    """Split a multi-value field (Splunk uses newlines or pipes or commas)."""
    if not raw or raw.strip() in ("", "NULL", "null"):
        return []
    return [v.strip() for v in re.split(r"[\n|,;]+", raw) if v.strip()]


# ---------------------------------------------------------------------------
# Emitter helpers
# ---------------------------------------------------------------------------

class ZilEmitter:
    def __init__(self, out):
        self._out = out

    def line(self, s=""):
        self._out.write(s + "\n")

    def comment(self, s):
        self.line(f"// {s}")

    def fact(self, subject, relation, obj):
        self.line(f"{subject}#{relation}@{obj}.")

    def macro(self, name, *args):
        args_str = ", ".join(str(a) for a in args)
        self.line(f"USE {name}({args_str}).")


# ---------------------------------------------------------------------------
# Main conversion
# ---------------------------------------------------------------------------

def convert(csv_path: str, out_path: str, opts: argparse.Namespace):
    module = opts.module or "sftp.activity"
    window_start = opts.window_start or ""
    window_end = opts.window_end or str(date.today())
    window_days = str(opts.window_days or 365)
    forced_server = _token(opts.server_id) if opts.server_id else None

    rows = []
    with open(csv_path, newline="", encoding="utf-8-sig") as f:
        reader = csv.DictReader(f)
        # Normalize header names (strip spaces, lowercase)
        reader.fieldnames = [h.strip().lower() for h in (reader.fieldnames or [])]
        for row in reader:
            rows.append({k.strip().lower(): v for k, v in row.items()})

    if not rows:
        print(f"No rows found in {csv_path}", file=sys.stderr)
        sys.exit(1)

    # Determine servers present
    servers = set()
    for row in rows:
        sid = forced_server or _token(row.get("server_id", row.get("server-id", "")))
        if sid:
            servers.add(sid)

    with open(out_path, "w", encoding="utf-8") as f:
        e = ZilEmitter(f)
        e.line(f"MODULE {module}.")
        e.line()
        e.comment(f"Generated by splunk-activity-to-zil.py")
        e.comment(f"Source: {os.path.basename(csv_path)}")
        e.comment(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}")
        e.comment(f"Observation window: {window_start or 'unknown'} → {window_end} ({window_days} days)")
        e.line()

        # Observation window metadata
        for sid in sorted(servers):
            if window_start:
                e.macro("SFTP_ACTIVITY_WINDOW",
                        sid, window_start, window_end, window_days)
        e.line()

        # Per-user facts
        current_server = None
        for row in sorted(rows, key=lambda r: (
            forced_server or _token(r.get("server_id", r.get("server-id", ""))),
            r.get("username", "")
        )):
            username_raw = row.get("username", "").strip()
            if not username_raw:
                continue

            server_id = forced_server or _token(row.get("server_id", row.get("server-id", "")))
            username = _token(username_raw)
            transfer_count = row.get("transfer_count", "0").strip() or "0"
            total_bytes = row.get("total_bytes", row.get("bytes_out", "0")).strip() or "0"
            session_count = row.get("session_count", row.get("dc(session_id)", "0")).strip() or "0"
            last_activity = row.get("last_activity", "").strip()

            if server_id != current_server:
                e.comment(f"--- server: {server_id} ---")
                current_server = server_id

            tc = int(transfer_count) if transfer_count.isdigit() else 0

            if tc == 0:
                e.macro("SFTP_USER_NO_ACTIVITY", username, server_id)
            else:
                e.macro("SFTP_USER_ACTIVITY",
                        username, server_id, last_activity or "unknown",
                        transfer_count, total_bytes, session_count)

            # Source IPs
            raw_ips = row.get("source_ips", row.get("ips", ""))
            for ip in _split_multival(raw_ips):
                ip_tok = _token(ip.replace(".", "_"))
                e.macro("SFTP_USER_SOURCE_IP", username, server_id, ip_tok)
                # Preserve the raw IP as a fact so queries can show it
                e.fact(f"sftp:user_activity:{server_id}:{username}",
                       "source_ip_raw", f'value:"{ip}"')

            # Path prefixes
            raw_paths = row.get("paths", row.get("sample_paths", ""))
            seen_prefixes = set()
            for p in _split_multival(raw_paths):
                prefix = _prefix_from_path(p)
                tok = _token(prefix)
                if tok not in seen_prefixes:
                    seen_prefixes.add(tok)
                    e.macro("SFTP_USER_PATH_PREFIX", username, server_id, tok)
                    e.fact(f"sftp:user_activity:{server_id}:{username}",
                           "path_prefix_raw", f'value:"{prefix}"')

            e.line()

    active = sum(1 for r in rows if int(r.get("transfer_count", "0") or "0") > 0)
    inactive = len(rows) - active
    print(f"Wrote {out_path}")
    print(f"  rows: {len(rows)} total  ({active} active, {inactive} inactive)")
    print(f"  servers: {', '.join(sorted(servers))}")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main():
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("input_csv", help="Splunk CSV export path")
    p.add_argument("output_zc", help="Output ZIL model path")
    p.add_argument("--server-id",
                   help="Override server_id for all rows (use ZIL token form, e.g. s_1234567890abcdef0)")
    p.add_argument("--window-start", metavar="YYYY-MM-DD",
                   help="Start of Splunk observation window")
    p.add_argument("--window-end", metavar="YYYY-MM-DD",
                   help="End of observation window (default: today)")
    p.add_argument("--window-days", type=int, default=365,
                   help="Number of days covered (default: 365)")
    p.add_argument("--module",
                   help="ZIL module name (default: sftp.activity)")
    opts = p.parse_args()
    convert(opts.input_csv, opts.output_zc, opts)


if __name__ == "__main__":
    main()
